### ISSUE TITLE
Report the bug of @typings/assert

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#101]

**Comment by streamcode9** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14708

**Comment by nponeccop** [comment]
Воспроизведи баг с tsc на винде. А то чинить не будут подумают он только в студии а студию типа никто не юзает как и винду.

**Comment by streamcode9** [comment]
Воспроизвел. Обновил описание.
