### ISSUE TITLE
d3-myaxis-ts breaks when running from file:// URL

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#17]
Unable to get property 'length' of undefined or null reference

**Comment by streamcode9** [comment]
What is browser version? I can't reproduce it. What are the steps?

**Comment by nponeccop** [comment]
Oh, sorry. `d3-myaxis` works but `d3-myaxis-ts` doesn't. I'll change the title.

**Comment by nponeccop** [comment]
Works fine from a web server. The problem is only with running from `file://` URL

**Comment by nponeccop** [comment]
It only breaks in Edge. In FF `file://` works just fine

**Comment by streamcode9** [comment]
In chrome breaks too
