### ISSUE TITLE
Missing grid lines and labels after fast drag on Android

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#20]
It seems that D3 `enter`-`exit` events are broken. We need to reproduce that with non-modified upstream code and file a bug there.

**Comment by nponeccop** [comment]
We need Demo2 gist/bl.ocks so I can show it to the original reporter

**Comment by streamcode9** [comment]
https://bl.ocks.org/streamcode9/raw/9fc767e29414c2d90f77da4799b9fdf0/

**Comment by nponeccop** [comment]
http://nponeccop.livejournal.com/547496.html

**Comment by nponeccop** [comment]
Can't reproduce
