### ISSUE TITLE
Abbreviated K-M-G ticks on vertical axis

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#25]
It may be supported by d3-scale out of the box

**Comment by streamcode9** [comment]
d3 has it for Dates, but not for numbers

**Comment by nponeccop** [comment]
Похоже надо scale поправить. Т.е. надписями не d3-axis а d3-scale занимается. Хез какой API там - может надо linearScale пропатчить, а может есть документированный способ поменять форматирование меток.
