### ISSUE TITLE
Use d3 modules instead of monolithic version

### ISSUE THREAD

**Issue by streamcode9** [streamcode9/svg-time-series#30]
- [x] axis-draw-transform
- [ ] demo2-without-grid
- [x] segment-tree-queries
- [x] sine-transform-d3
- [x] svg-path-recreation-d3
- [x] /draw.ts
- [ ] demo1
- [x] demo2
- [ ] remove monolithic `d3` from `package.json`

**Comment by nponeccop** [comment]
Most of the original issues are fixed. The rest will be  be fixed in #89. I'm leaving it open but no longer priority as we need to get rid of monolitic `d3` in package.json eventually.
