### ISSUE TITLE
Use stock d3 in d3-fixedaxis

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#39]
The changes from d3-fixedaxis are in alpha 50, so copy-pasting git HEAD version of d3-axis is not necessary any more.

**Comment by streamcode9** [comment]
Do we still need d3-fixedaxis version?

**Comment by nponeccop** [comment]
We need a pair of benchmarks which compares our axis to stock D3 axis.

I think of something like `benchmarks/axis-orig` and `benchmarks/axis-patched` which are the same in every aspect but usage of stock axis vs `../../axis.ts`.

The intention is that we can monitor the progress of upstream axis and get rid of `axis.ts` when the upstream gets fast enough.

**Comment by nponeccop** [comment]
The task is better described in #82 to avoid confusion.
