### ISSUE TITLE
Handle missing data

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#46]
The original data has gaps which seem to be handled incorrectly. As a result:
- the blue line is much shorter than the green one. In the original data, it is only short by one datapoint.
- realtime data are added to blue line in the past instead of in the present.

**Comment by streamcode9** [comment]
How to determine that ` data are added to blue line in the past`?
I do the same actions for both lines:
```ts
chart.data[0].values.push(chart.data[0].values[0])
chart.data[1].values.push(chart.data[1].values[0])
chart.data[0].values.shift()
chart.data[1].values.shift()
```

**Comment by nponeccop** [comment]
It looks like your initial importing of `char.data` from CSV handles missing data incorrectly - e.g. it doesn't push NaN if there is no data. Assert that all the series have the same array length

**Comment by streamcode9** [comment]
I've added handling of NaN values.
https://bl.ocks.org/streamcode9/raw/3042f96eb184994ae18a3338d2d2cb30/
Is it what we need?

**Comment by nponeccop** [comment]
Yes.
