### ISSUE TITLE
Phone-friendly demo

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#51]
LG D410 Android browser displays Demo 3 as scaled-out so the text is too small and grid has aliasing artifacts. The native resolution is 480x960.

Note that ultra-high resolution is problematic too, as 140px high is too small on 1080x1920 mobile screen.

Now the demo has a fixed 960px width. I'm not sure how to make a responsive design.

- [x] Horizontal scroll
- [x] Aliasing (try to decrease geometry precision)
- [x] Font size (top margin can be decreased)
- [x] Make sure that 5 charts fit to the page without vertical scrolling
- [x] Wrap charts with DIV, determine its size with clientWidth() on resize and set size of each SVG chart
- [x] Move single chart functionality to separate class
- [x] Resolutions https://files.gitter.im/streamcode9/svg-time-series/8O0I/Resolv.PNG and 540x960 mobile, 1366х768 desktop (fonts are fine), iPhone 1080х1920, desktop 1920х1080, retina
- [x] Space between charts is too big at desktop
- [x] Add bottom margin for the last chart

**Comment by streamcode9** [comment]
Wrap charts with DIV, determine its size on resize and set size of each SVG chart.

**Comment by streamcode9** [comment]
Determine size via .clientWidth

**Comment by streamcode9** [comment]
Move single chart functionality to separate class
