### ISSUE TITLE
Benchmark all components separately

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#57]
We need non-interactive benchmarks to measure overhead of individual components so we can put up a table of performance on different devices.

- [x] Path drawing and transformation (draw only charts and pan them on timer)
   - path-draw-transform-d3 pan to left right only
   - calculate smooth transformation/animation based on rAF time parameter with sinus function
   - chart should not exceed document borders
   - stop benchmark after minute and provide result FPS
- [x] Grid drawing and transformation (draw only axis and pan it on timer, see also #34)
- [x] SegmentTree reindexing (time to rebuild index 1000 times)
- [x] SVG DOM Path recreation (push new datapoint on every redraw and measure fps)
- [x] SegmentTree Queries 
   - draw only every 10th point but index the full dataset
   - pan chart on every redraw
   - autoscale using the full SegmentTree index
   - measure FPS

**Comment by streamcode9** [comment]
Benchmark 1 and 4 items with and without d3.

**Comment by nponeccop** [comment]
The following moved to #71 instead: 
- use CSS translate3d transformation
 - path-draw-transform-d3 version with SVG Animation (SMIL or CSS, if there is no universal solution leave current solution)

So the only bench remaining is "demo2 without grid"

**Comment by nponeccop** [comment]
Demo2 is moved to #72 so this one is done :)
