### ISSUE TITLE
Precalculate segment tree for fast Range Minimum Query

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#6]
https://en.wikipedia.org/wiki/Range_minimum_query
https://en.wikipedia.org/wiki/Fenwick_tree
https://en.wikipedia.org/wiki/Segment_tree
http://www.geeksforgeeks.org/segment-tree-set-1-range-minimum-query/

http://nponeccop.livejournal.com/422741.html?thread=3801429#t3801429 (in Russian)

**Comment by streamcode9** [comment]
I've integrated segment tree. Chrome and Edge shows 52-59 FPS, Firefox 19-46 FPS. What is acceptance criteria for this task?

**Comment by nponeccop** [comment]
A working segment tree. Performance is a non-goal here.

**Comment by streamcode9** [comment]
```ts
function generateArray() {
    let ys: number[] = []
    for (let i = 0; i < 1000; i++) {
        ys.push(Math.random())
    }
    return ys
}

function generateData() {
    let xs: any[] = []
    for (let j = 0; j < 5; j++) {
        xs.push([{ values: generateArray() }, { values: generateArray() }])
    }
    return xs
}

let benchmarks: any[] = []

for (let j = 0; j < 1000; j++) {
    let data: any = generateData()

    let start = new Date()
    for (let i = 0; i < data.length; i++) {
        new SegmentTree(data[i], data[i][0].values.length, buildTupleFunction)
    }
    let end = new Date()

    benchmarks.push(end.getTime() - start.getTime())
}

console.log(benchmarks)
```
It takes less than 1ms to build a tree. I suggest to rebuild tree for now and optimize in future if it becomes a problem. What do you think?

**Comment by nponeccop** [comment]
I agree
