### ISSUE TITLE
Windows instruction misses Git and Web Development Tools

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#69]
### Build instructions for Windows (to review)
1. Install MSVS 2015 community (make sure you have Update 3 installed)
2. Install Microsoft ASP.NET and Web Tools (if it has not been installed with MSVS 2015)
3. Install latest TypeScript tools for MSVS 2015 2.x.x
4. Install nodejs (npm will be also installed)
5. Open project in VS -> package.json -> Right click -> Restore dependencies
6. Build project

**Comment by genuisereal** [comment]
I installed web development tools and open solution. it is possible to build it without errors.

now how exactly to start anything? 
Start button in studio shows Firefox browser by default. When pressed it show ~Debugging not enabled dialog. I select Run without debugging and press OK. 
New Firefox tab is opened, but with error message 
"HTTP Error 403.14 - Forbidden
The Web server is configured to not list the contents of this directory."

**Comment by streamcode9** [comment]
browserify should be at devDependencies of package.json

**Comment by genuisereal** [comment]
после установки node.js (если не был установлен) будет доступен npm
npm install browserify
без глобального ключа

запуск на исполнение с относительнім путем
..\..\node_modules\.bin\browserify index.js -o bundle.js

**Comment by streamcode9** [comment]
- browserify должно быть прописано в devDependencies в package.json
  - флаг -g это моветон
  - запускать правильно через npm run browserify
  - билд тул какой-то юзать типа brunch или gulp
  - Ещё надо придумать dev mode чтобы ts сам перекомпилировался по рефрешу, и в браузере можно было ts отлаживать через sourceMap
  - бандл перебандливаеться должен сам
  - добавить авто билда и отладку тайпскрипта и перегрузку браузера (некоторые фреймворки умеют сами себя перегружать в браузере если исходники поменялись)

**Comment by genuisereal** [comment]
у меня вчера так и не получилось запустить browserify 
ни через npm run browserify 
ни через npm run ..\..\node_modules\.bin\browserify

**Comment by streamcode9** [comment]
- development-mode
   - https://www.npmjs.com/package/browserify-middleware
    - можно 10-строчный статик-сервер на ноде запустить, чтобы по рефрешу переминифицировал
но в студии должен быть какой-то официальный вариант, тайпскрипт же прежде всего для браузера позиционируют

**Comment by streamcode9** [comment]
* по студии у нас другая задача - чтобы можно было поставить брейкпоинт в студии и пустить по F5, без ручного открытия отладчика в браузере. Нужно хоть какое-то решение, пусть даже ценой отказа от browserify

**Comment by nponeccop** [comment]
https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/

может стоит обновиться вам? у меня 2.1.4 в линуксе если что.

**Comment by genuisereal** [comment]
я проверил, студия говорит, что обновление будет автоматически

**Comment by nponeccop** [comment]
Ставит пакаджи не tsc а npm. Т.е. сначала надо решить проблему npm вот эту:

```
npm ERR! 404 'types/d3-selection' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 'types/d3-request' is not in the npm registry.
npm ERR! 404 'types/d3-selection' is not in the npm registry.
npm ERR! 404 'types/d3-timer' is not in the npm registry.
npm ERR! 404 'types/d3-timer' is not in the npm registry.
```
