### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/svg-time-series#72]
- [x] `demo2` - update to use `path-draw-transform-d3` approach
- [x] `axis-draw-transform` 
   - [x] update to match `demo2` fixes from `path-draw-transform-d3`
   - [x] remove segment tree, our dataset, cities etc
- [x] `segment-tree-queries`
   - [x] fix `const minMax = tree.getMinMax(0, tree.size - 1)`, range should be based on minX and maxX
- [x] `segment-tree-reindexing`
- [x] `svg-path-recreation`

**Comment by streamcode9** [comment]
Build segment tree based on data from d3 line accessor.

**Comment by streamcode9** [comment]
It is easier to remove line from path-draw-transform-d3 add grid to get axis-draw-transform.

**Comment by nponeccop** [comment]
Те ишшуи про которые было написано "отдельные низкоприоритетные" вынес в #89. Туда же поместил demo2-without-grid. Поскольку грид таки рано или поздно придется переделывать и бенчить детальнее.

**Comment by nponeccop** [comment]
Fixed minmax in segment-tree-queries

**Comment by nponeccop** [comment]
Починил последние проблемы демо2 (зум и счетчик FPS) в 72b2c0f
