### ISSUE TITLE
Implement custom transformers instead of d3-scale

### ISSUE THREAD

**Issue by streamcode9** [streamcode9/svg-time-series#74]
- идея написать классы-трансформеры {a : number, b: number} (на самом деле двухэлементные матрицы) которые из X делают a * x + b, их конструкцию из minIn, maxIn, minOut, maxOut и композицию и потом собирать атрибуты трансформации SVG из нормальных примитивов. написать классы-трансформеры с операцией композиции или хотя бы использовать SVGPoint и SVGMatrix в рассчётах в draw.ts
- было x = d3.linearScale().domain(minIn, maxIn).range(minOut, maxOut)
- внутри x у нас линейная формула: scale.x = function (x) { return a * x + b }
- надо сделать аналог чтобы эти a и b можно было вытащить наружу и оперировать ими отдельно
- Погорелов. умножение вектора на скаляр. аффинные преобразования и группа поворотов

**Comment by nponeccop** [comment]
@genuisereal сейчас пилит прототип на основе нашего `benchmarks/dom/`, как запилит пришлет пулл-реквест или коммит.

**Comment by nponeccop** [comment]
Я хотел предложить сделать свой трансформ лист в виде массива SVG Matrix
Помогут тем что отдельно висящий объект матрица можно создать
В отличие от трансформа который всегда прилеплен к дому

**Comment by nponeccop** [comment]
Fixed in #91
