### ISSUE TITLE
Zoom state is reset randomly

### ISSUE THREAD

**Issue by streamcode9** [streamcode9/svg-time-series#98]
Possible steps to reproduce:
1 - Open Edge
2 - Zoom to max
3 - Make another tab active
4 - Return to charts tab
5 - Try to pan

----

`d3event.transform` contains `Transform {k: 1, x: 0, y: 0}` when zoom occurs, but values are wrong. `k` parameter must be 40.
After a minute of inactivity, another zoom event is risen and  contains valid values again `Transform {k: 40, x: -28571.44122104238, y: -2264.321745211511}`

----
Steps to reproduce:
1 - Pan/zoom on first chart.
2 - Pan/zoom on last chart. In this moment pan/zoom transform will be reset.

**Comment by nponeccop** [comment]
See also #42
